#ifndef _IRIDIUMDEFINES_H_
#define _IRIDIUMDEFINES_H_

#define SATELLITE_COUNT 66
#define GATE_COUNT 7
#define NODE_COUNT SATELLITE_COUNT+GATE_COUNT
#define PLANE 6
#define SATELLITE_PER_PLANE 11

#define S2S_REL 0.99
#define S2G_REL 0.995

#endif
